version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    networks:
      - laravel-network

  webserver:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8001:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
    networks:
      - laravel-network

  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: momo12
      POSTGRES_PASSWORD: momo123
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - laravel-network

networks:
  laravel-network:

volumes:
  db_data:
